[package]
name = "rltkwalkthrough"
version = "0.1.0"
authors = ["erika jonell <erika.jonell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = {version = "0.8.1"}